# Generated by Django 3.0.5 on 2020-05-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('address', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrentals.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrentals.Province')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=255, unique=True)),
                ('id_number', models.CharField(max_length=255, unique=True)),
                ('cell_number', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('kin_number', models.IntegerField(blank=True, null=True)),
                ('kin_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('kin_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tenant', to='propertyrentals.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=255, unique=True)),
                ('id_number', models.CharField(max_length=255, unique=True)),
                ('cell_number', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('kin_number', models.IntegerField(blank=True, null=True)),
                ('kin_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('kin_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_agent', to='propertyrentals.Town')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_two', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrentals.Country')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_addresses', to='propertyrentals.Property')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrentals.Province')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrentals.Town')),
            ],
        ),
    ]
