# Generated by Django 3.0.5 on 2020-05-06 10:33

from django.db import migrations
from propertyrentals.models import *

def create_locations(apps, schema_edit):
    Country.objects.get_or_create(name='South Africa', code='ZA')
    Province.objects.get_or_create(country_id=1, name='Western Cape', code='WC')
    Province.objects.get_or_create(country_id=1, name='Eastern Cape', code='EC')
    Province.objects.get_or_create(country_id=1, name='Northern Cape', code='NC')
    Province.objects.get_or_create(country_id=1, name='Nort West', code='NW')
    Province.objects.get_or_create(country_id=1, name='Free State', code='FS')
    Province.objects.get_or_create(country_id=1, name='Kwazulu Natal', code='KZN')
    Province.objects.get_or_create(country_id=1, name='Gauteng', code='GP')
    Province.objects.get_or_create(country_id=1, name='Limpopo', code='L')
    Province.objects.get_or_create(country_id=1, name='Mpumalanga', code='MP')

    Town.objects.get_or_create(name='Cape Town', code='CA', province_id=1)

class Migration(migrations.Migration):

    dependencies = [
        ('propertyrentals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_locations)
    ]
