# Generated by Django 3.0.5 on 2020-08-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrentals', '0003_auto_20200506_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('initials', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
