# Generated by Django 3.0.5 on 2020-08-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrentals', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(max_length=150),
        ),
    ]
