# Generated by Django 3.0.5 on 2021-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsubscription', '0002_auto_20210405_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cell_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], max_length=255, null=True),
        ),
    ]
