# Generated by Django 3.0.5 on 2021-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsubscription', '0003_auto_20210406_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
